apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 4 #optional, default is 1
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: pewxh/test_server
          ports:
            - containerPort: 80
