apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    name: sample-pod
spec:
  containers:
    - name: sample-server-container
      image: pewxh/test_server
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
